spring:
  profiles.active: dev
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    username: SA
    password: ""
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:hsqldb:mem:archapp_dev;shutdown=true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:hsqldb:mem:archapp;shutdown=true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:hsqldb:mem:archapp_test;shutdown=true